### ISSUE TITLE
Module not found errors of index.js and foreign.js

### ISSUE THREAD

**Issue by AlexaDeWit** [ethul/purs-loader#111] opened 2018-06-08 22:33 UTC
I've attempted to predominantly mimic the example you link, but am at a total loss after several hours as to why it is trying to require files with these names in the first place.

From what I understand this is going wrong internally within webpack when it's attempting to "require" the files resulting from compilation. My suspicion is that because the purescript compiler for 0.12 outputs compiled files to a separate "output" folder, which then isn't resolving.

If I find the solution I'll add it here, and you can lose the issue, but at least a closed issue might help the next person who loses their mind like me :dancer: 

Here's a few examples: 

```
ERROR in ./bower_components/purescript-prelude/src/Data/Ord.purs
Module not found: Error: Can't resolve '../Data.Ordering/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data'
 @ ./bower_components/purescript-prelude/src/Data/Ord.purs 6:20-56
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/Ord/Unsafe.purs
Module not found: Error: Can't resolve '../Data.Ordering/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data/Ord'
 @ ./bower_components/purescript-prelude/src/Data/Ord/Unsafe.purs 4:20-56
 @ ./bower_components/purescript-prelude/src/Data/Ord.purs
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Prelude.purs
Module not found: Error: Can't resolve '../Data.Ring/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src'
 @ ./bower_components/purescript-prelude/src/Prelude.purs 24:16-48
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/Field.purs
Module not found: Error: Can't resolve '../Data.Ring/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data'
 @ ./bower_components/purescript-prelude/src/Data/Field.purs 6:16-48
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/CommutativeRing.purs
Module not found: Error: Can't resolve '../Data.Ring/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data'
 @ ./bower_components/purescript-prelude/src/Data/CommutativeRing.purs 3:16-48
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/Ord.purs
Module not found: Error: Can't resolve '../Data.Ring/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data'
 @ ./bower_components/purescript-prelude/src/Data/Ord.purs 7:16-48
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/DivisionRing.purs
Module not found: Error: Can't resolve '../Data.Ring/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data'
 @ ./bower_components/purescript-prelude/src/Data/DivisionRing.purs 4:16-48
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/EuclideanRing.purs
Module not found: Error: Can't resolve '../Data.Ring/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data'
 @ ./bower_components/purescript-prelude/src/Data/EuclideanRing.purs 8:16-48
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/Function.purs
Module not found: Error: Can't resolve '../Data.Ring/index.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data'
 @ ./bower_components/purescript-prelude/src/Data/Function.purs 6:16-48
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Data/Ord/Unsafe.purs
Module not found: Error: Can't resolve './foreign.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Data/Ord'
 @ ./bower_components/purescript-prelude/src/Data/Ord/Unsafe.purs 3:15-38
 @ ./bower_components/purescript-prelude/src/Data/Ord.purs
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

ERROR in ./bower_components/purescript-prelude/src/Record/Unsafe.purs
Module not found: Error: Can't resolve './foreign.js' in '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-prelude/src/Record'
 @ ./bower_components/purescript-prelude/src/Record/Unsafe.purs 3:15-38
 @ ./bower_components/purescript-prelude/src/Data/Eq.purs
 @ ./bower_components/purescript-prelude/src/Prelude.purs
 @ ./src/App.purs
 @ multi (webpack)-dev-server/client?http://localhost:4008 webpack/hot/dev-server ./src/App.purs

```

**Comment by AlexaDeWit** [comment] 2018-06-08 22:48
https://github.com/AlexaDeWit/MySelfcareClient

For context, that's the repository where I've begun setting up the build chain before I get started on the application.

**Comment by ethul** [comment] 2018-06-08 23:05
Thanks so much for digging into this. I believe the issue is due to a change in the JS output in PS 0.12 compared to 0.11. 

### PS 0.11
```js
var Control_Bind = require("../Control.Bind");

var $foreign = require("./foreign");
```

### PS 0.12
```js
var Control_Bind = require("../Control.Bind/index.js");

var $foreign = require("./foreign.js");
```

We would need to update the following regular expressions to fix this I think.

https://github.com/ethul/purs-loader/blob/2b017f9a225668f160ffca88b9b6efe01133a460/src/to-javascript.js#L72-L74

**Comment by ethul** [comment] 2018-06-09 18:50
I think updating those REs to the following does the trick.

```js
  const requireRE = /require\(['"]\.\.\/([\w\.]+)(?:\/index\.js)?['"]\)/g;

  const foreignRE = /require\(['"]\.\/foreign(?:\.js)?['"]\)/g;
```

**Comment by AlexaDeWit** [comment] 2018-06-09 19:27
I changed it in-place, the new result is that I hang here.

```alexa@alexa-desktop:~/Workspace/my-selfcare-client$ yarn run webpack:server
yarn run v1.5.1
warning package.json: License should be a valid SPDX license expression
$ webpack-dev-server --progress --inline --hot
 10% building modules 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4008/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from .
 10% building modules 8/9 modules 1 active …rkspace/my-selfcare-client/src/App.purs(node:30974) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 20% building modules 84/167 modules 83 active …escript-nullable/src/Data/Nullable.pursglob error { Error: EMFILE: too many open files, scandir '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-web-html/src/Web/HTML/Event/BeforeUnloadEvent'
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-web-html/src/Web/HTML/Event/BeforeUnloadEvent' }
 20% building modules 84/170 modules 86 active …nts/purescript-web-dom/src/Web/DOM.pursglob error { Error: EMFILE: too many open files, scandir '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-aff/src'
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-aff/src' }
glob error { Error: EMFILE: too many open files, scandir '/home/alexa/Workspace/my-selfcare-client/bower_components'
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/home/alexa/Workspace/my-selfcare-client/bower_components' }
glob error { Error: EMFILE: too many open files, scandir '/home/alexa/Workspace/my-selfcare-client/src'
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/home/alexa/Workspace/my-selfcare-client/src' }
 20% building modules 87/170 modules 83 active …nts/purescript-web-dom/src/Web/DOM.pursglob error { Error: EMFILE: too many open files, scandir '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-arrays/src/Data/Array/NonEmpty'
  errno: -24,
  code: 'EMFILE',
  syscall: 'scandir',
  path: '/home/alexa/Workspace/my-selfcare-client/bower_components/purescript-arrays/src/Data/Array/NonEmpty' }
 23% building modules 112/212 modules 100 active …html/src/Web/HTML/HTMLOListElement.purs

```

**Comment by ethul** [comment] 2018-06-09 19:29
Which version of node are you using? I tried the RE change on a small project and it seemed to work okay.

**Comment by ethul** [comment] 2018-06-09 19:31
Maybe something from this thread could help find the issue?
https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

**Comment by AlexaDeWit** [comment] 2018-06-09 19:32
v8.11.1
is my current version.

Perhaps the size of the project here is the issue, as I have halogen and purescript-css in my output directory?

**Comment by AlexaDeWit** [comment] 2018-06-09 19:33
Or it may just be my webpack config. I'll try and look at it in a bit.

**Comment by ethul** [comment] 2018-06-09 19:34
Thanks for taking a look. It might be worth to try graceful-fs.

**Comment by ethul** [comment] 2018-06-09 19:40
I am guessing the issue is when the module mapping is created and all the PureScript files are read.

https://github.com/ethul/purs-loader/blob/2b017f9a225668f160ffca88b9b6efe01133a460/src/purs-module-map.js#L64-L74

Maybe there is a better approach here.

**Comment by AlexaDeWit** [comment] 2018-06-09 19:52
I've changed the config to something more similar to your example one, and the issue persists I'm afraid.

**Comment by AlexaDeWit** [comment] 2018-06-09 19:52
are you able to replicate the issue if you clone my project for instance? (it's not big)

**Comment by ethul** [comment] 2018-06-10 12:42
I gave your repository a try. Running `yarn webpack` seems to work okay for me.

**Comment by AlexaDeWit** [comment] 2018-06-10 15:57
Deeply strange...

This is what I end up with:

```  purs-loader:verbose loading JavaScript for Intl +1ms
ModuleNotFoundError: Module not found: Error: Can't resolve '../Button/index.js' in '/home/alexa/Workspace/my-selfcare-client/src'
    at factory.create (/home/alexa/Workspace/my-selfcare-client/node_modules/webpack/lib/Compilation.js:535:10)
    at factory (/home/alexa/Workspace/my-selfcare-client/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/alexa/Workspace/my-selfcare-client/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/alexa/Workspace/my-selfcare-client/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/alexa/Workspace/my-selfcare-client/node_modules/neo-async/async.js:2817:7
    at /home/alexa/Workspace/my-selfcare-client/node_modules/neo-async/async.js:6783:13
    at normalResolver.resolve (/home/alexa/Workspace/my-selfcare-client/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:181:12)
    at hook.callAsync (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/home/alexa/Workspace/my-selfcare-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/home/alexa/Workspace/my-selfcare-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/home/alexa/Workspace/my-selfcare-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn42 (eval at create (/home/alexa/Workspace/my-selfcare-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:393:1)
    at hook.callAsync (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/home/alexa/Workspace/my-selfcare-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn1 (eval at create (/home/alexa/Workspace/my-selfcare-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at hook.callAsync (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
    at _fn0 (eval at create (/home/alexa/Workspace/my-selfcare-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at fs.stat (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
    at process.nextTick (/home/alexa/Workspace/my-selfcare-client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
resolve '../Button/index.js' in '/home/alexa/Workspace/my-selfcare-client/src'
  using description file: /home/alexa/Workspace/my-selfcare-client/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/alexa/Workspace/my-selfcare-client/package.json (relative path: ./Button/index.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/alexa/Workspace/my-selfcare-client/Button/index.js doesn't exist
      .purs
        Field 'browser' doesn't contain a valid alias configuration
        /home/alexa/Workspace/my-selfcare-client/Button/index.js.purs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/alexa/Workspace/my-selfcare-client/Button/index.js.js doesn't exist
      as directory
        /home/alexa/Workspace/my-selfcare-client/Button/index.js doesn't exist
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c DEBUG=purs-loader* DEBUG_DEPTH=100 webpack --progress --bail
Directory: /home/alexa/Workspace/my-selfcare-client
Output:
".
```

Pulp however has no difficulty producing both blob and browserify-style outputs.

**Comment by spicydonuts** [comment] 2018-06-14 04:48
Is this blocking all purescript 0.12.0 projects or a specific case? Just ran into it while updating one of our projects.

**Comment by ethul** [comment] 2018-06-14 09:34
Thanks for the PR. I've merged it while we work on this issue.

**Comment by ethul** [comment] 2018-12-06 18:47
Thanks for the update to this issue. Just to confirm, what version of PureScript is being used? If you cloned the purescript-webpack-example, then it might be [0.11](https://github.com/ethul/purescript-webpack-example/blob/ca9a656f9278d34a75194d7bf69a24eebc9771ce/package.json#L24).

**Comment by adnelson** [comment] 2018-12-10 22:08
Looking at `node_modules/purescript/package.json`, the version is 0.12.1. Is that a potential issue?

**Comment by ethul** [comment] 2018-12-11 01:57
Thanks for confirming. This is definitely an issue. The problem is that the loader is not handling the relative import in [`Data/HashMap.js`](https://github.com/fehrenbach/purescript-unordered-collections/blob/d8f96e486e23fec4ef66800e724a31d3d008be69/src/Data/HashMap.js#L9). I will open this in a new issue for tracking. Thanks again!

**Comment by ethul** [comment] 2018-12-11 19:22
Closing because I believe the original issue in this post has been resolve. Moving [further discussion](https://github.com/ethul/purs-loader/issues/111#issuecomment-444634769) to #115.

**Closed by ethul** 2018-12-11 19:22 UTC
