### ISSUE TITLE
purs-loader doesn't appear to handle imported Purescript dependencies properly

### ISSUE THREAD

**Issue by iand675** [ethul/purs-loader#37] opened 2016-02-18 04:16 UTC
I've got a project with multiple purescript modules. When I save any purescript file that isn't explicitly required in the entry script file while running `webpack --watch`, the changed modules don't trigger a rebuild.

**Comment by ethul** [comment] 2016-02-18 14:54
Thanks for the report. I am wondering if you have your project available online or if you have a small example that illustrates the issue. I will have to dig into this a bit more though.

**Comment by iand675** [comment] 2016-02-19 02:05
Here's a sample project that repros the issue for me: https://github.com/iand675/purescript-loader-reload-issue-repro

To reproduce the issue:

run `./node_modules/.bin/webpack --watch`. Make a real change to the `entry.js` file. The bundle should be rebuilt, as expected. Make a change to `Main.purs` that actually causes the generated output to be different, like adding a new function. The bundle should rebuild, as expected. Now, try making a change to `Other.purs`. Regardless of what I do, the bundle doesn't rebuild. I think that for some reason the purescript loader doesn't track transitive dependencies.

**Comment by ethul** [comment] 2016-02-19 02:09
Great. Thank you so much for putting the example together. I will take a
look.

**Comment by ethul** [comment] 2016-02-19 04:12
Good find. The loader should handle transitive dependencies. I will work on a fix to call `addDependency` on the imports. I am thinking I will have to do this for all transitive imports. I will look into it though. I am open to ideas and suggestions too. Thanks again for the report on this.

**Comment by iand675** [comment] 2016-02-19 04:20
I think the other thing is making sure that you call addDependencies for FFI js files. In a use case that I have at the moment, I `require` an svg that webpack transforms into a react component, which I then import via the FFI. Changes to that svg ought to trigger a rebuild as well.

**Comment by ethul** [comment] 2016-02-19 04:27
Yes. Good point.

**Comment by ethul** [comment] 2016-02-25 04:06
I have a rough cut at a solution. Would you be willing to test it on your use-case by installing the loader and plugin at the following commits?

```
ethul/purs-loader#f97818b550b17455448ff7fe09689b326c30912b
ethul/purescript-webpack-plugin#2792561d67c46069426edbf9c18f053ba9e5cfeb
```

Note that for the purs-loader, once you've installed it with npm, you have to:

```
cd node_modules/purs-loader
npm install
bower install
npm run build
```

This is because it is not published, just up on github not built yet.

I can cut an RC release if you prefer, but once we know this works, I would like to make some improvements on the changes before releasing the next version.

**Comment by iand675** [comment] 2016-02-26 01:41
So I tried following those instructions, and it failed with a `pulp` error:
```
> purs-loader@0.5.0 prepublish /Users/ian/Public/Drop Box/Code/Code/betterteam/frontend/node_modules/purs-loader
> npm run-script build


> purs-loader@0.5.0 build /Users/ian/Public/Drop Box/Code/Code/betterteam/frontend/node_modules/purs-loader
> npm run-script build:compile && npm run-script build:docs && npm run-script build:package


> purs-loader@0.5.0 build:compile /Users/ian/Public/Drop Box/Code/Code/betterteam/frontend/node_modules/purs-loader
> pulp build -o build --force

* Building project in /Users/ian/Public/Drop Box/Code/Code/betterteam/frontend
Invalid option `--force'

Usage: psc [FILE] [-f|--ffi ARG] [-o|--output ARG] [--no-tco] [--no-magic-do]
           [--no-opts] [-v|--verbose-errors] [-c|--comments]
           [-r|--require-path ARG] [-p|--no-prefix]
* ERROR: Subcommand terminated with exit code 1

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "run-script" "build:compile"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! purs-loader@0.5.0 build:compile: `pulp build -o build --force`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the purs-loader@0.5.0 build:compile script 'pulp build -o build --force'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purs-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pulp build -o build --force
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purs-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purs-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ian/Public/Drop Box/Code/Code/betterteam/frontend/node_modules/purs-loader/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "run-script" "build"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! purs-loader@0.5.0 build: `npm run-script build:compile && npm run-script build:docs && npm run-script build:package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the purs-loader@0.5.0 build script 'npm run-script build:compile && npm run-script build:docs && npm run-script build:package'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purs-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script build:compile && npm run-script build:docs && npm run-script build:package
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purs-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purs-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ian/Public/Drop Box/Code/Code/betterteam/frontend/node_modules/purs-loader/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! purs-loader@0.5.0 prepublish: `npm run-script build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the purs-loader@0.5.0 prepublish script 'npm run-script build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the purs-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purs-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls purs-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ian/Public/Drop Box/Code/Code/betterteam/frontend/node_modules/purs-loader/npm-debug.log
```

It looks like there's an out of place `--force` flag? I'm running Node v.5.7.0, psc v0.7.6.1, pulp v8.0.0.

**Comment by iand675** [comment] 2016-02-26 01:42
(this is for running `npm install` in the `node_modules/purs-loader` directory, btw)

**Comment by ethul** [comment] 2016-02-26 01:46
Thanks for giving this a try. We must be on different pulp versions. Maybe
it is easiest if I publish a beta release. I can get this out soon.

**Comment by ethul** [comment] 2016-02-26 02:59
I've publish `purs-loader@0.6.0-beta.0` and `purescript-webpack-plugin@0.2.0-beta.0` to npm. Please give them a spin if you have a chance.

Thanks!

**Comment by iand675** [comment] 2016-02-26 09:25
Thanks for the responsiveness on this issue! Unfortunately, using the beta packages is even worse. Running webpack now does nothing at all: no error code, no console output.

**Comment by ethul** [comment] 2016-02-26 09:48
Welcome. Hmm. Something must be up with the release. I will take a look.
Thanks for testing.

**Comment by ethul** [comment] 2016-02-26 10:06
I double-checked the releases using the purs-loader example project and on your test project (https://github.com/iand675/purescript-loader-reload-issue-repro). Things seem to be working.

My test case was changing "Hello wibbles" to "Hello wibbles 111" rebuilt the bundle and the changes were reflected in the result.

Maybe there is something else going on. What OS version, PureScript version, etc. are you running?

Thanks!

**Comment by ethul** [comment] 2016-02-28 01:24
I am wondering if you've had any luck on this.

I've published new beta releases: `purs-loader@0.6.0-beta.1` and `purescript-webpack-plugin@0.2.0-beta.1`.

These use the [debug](https://www.npmjs.com/package/debug) package and provide some debug logging that might shed light on what is going on. In order to enable debugging you can invoke webpack as:

```
DEBUG=purescript-webpack-plugin,purs-loader ./node_modules/.bin/webpack -w
```

The important bit is the `DEBUG` environment variable. If you have time to give this a spin it would be great.

**Comment by osener** [comment] 2016-02-28 10:31
I updated a project I was playing with last month to latest beta versions, I'm now getting

```
ERROR in ./src/Actions.purs
Module build failed: Error: Node does not exist: Actions
    at Object.DepGraph.dependenciesOf (/home/ozan/vcs/react-transform-boilerplate/node_modules/dependency-graph/lib/dep_graph.js:139:13)
    at dependenciesOfFn (/home/ozan/vcs/react-transform-boilerplate/node_modules/purs-loader/index.js:3887:31)
    at /home/ozan/vcs/react-transform-boilerplate/node_modules/purs-loader/index.js:3501:19
    at /home/ozan/vcs/react-transform-boilerplate/node_modules/purs-loader/index.js:1979:17
    at /home/ozan/vcs/react-transform-boilerplate/node_modules/purs-loader/index.js:120:85
    at /home/ozan/vcs/react-transform-boilerplate/node_modules/purescript-webpack-plugin/index.js:180:76
    at Array.forEach (native)
    at /home/ozan/vcs/react-transform-boilerplate/node_modules/purescript-webpack-plugin/index.js:180:34
    at ChildProcess.<anonymous> (/home/ozan/vcs/react-transform-boilerplate/node_modules/purescript-webpack-plugin/index.js:127:5)
    at emitTwo (events.js:100:13)
 @ ./src/containers/App.jsx 27:15-41
```

Is it possible that the changes broke importing PureScript modules from JavaScript? If this is not as simple as this I can try to provide a testcase

**Comment by osener** [comment] 2016-02-28 10:42
Sorry, that was about a missing bower dependency. Downgrading to previous allowed me to see `Unknown module` errors from psc, but the betas are swallowing psc errors.

After installing the missing dependencies I'm now seeing the same behavior as @iand675. With debug it shows
```
  purs-loader Invoke PureScript plugin compilation +0ms
  purescript-webpack-plugin Compiling PureScript files +1ms
  purs-loader Invoke PureScript plugin compilation +14ms
  purescript-webpack-plugin Bundling compiled PureScript files +2s
  purescript-webpack-plugin Updating dependency graph of PureScript bundle +641ms
```

then hangs indefinitely

**Comment by ethul** [comment] 2016-02-28 12:29
@osener Thanks for testing this out and for the additional info. This definitely helps.

Out of curiosity, does webpack build your project correctly without using watch? Also, what version of PureScript are you using?

And just for reference, the expected debug output should include:
```
  purs-loader Invoke PureScript plugin compilation +0ms
  purescript-webpack-plugin Compiling PureScript files +0ms
  purescript-webpack-plugin Bundling compiled PureScript files +202ms
  purescript-webpack-plugin Updating dependency graph of PureScript bundle +108ms
  purescript-webpack-plugin Generating result for webpack +52ms
  purs-loader Adding PureScript dependency Main +382ms
  purs-loader Adding PureScript transitive dependencies for Main +1ms
...
```

So it seems there is something up after the update to the dependency graph.

**Comment by ethul** [comment] 2016-02-28 12:37
Okay. I was able to reproduce this using Purescript 0.8.0. I will see what's up!

**Comment by osener** [comment] 2016-02-28 12:48
Without --watch it just quits after
```
  purs-loader Invoke PureScript plugin compilation +0ms
  purescript-webpack-plugin Compiling PureScript files +4ms
  purs-loader Invoke PureScript plugin compilation +17ms
  purescript-webpack-plugin Bundling compiled PureScript files +10s
  purescript-webpack-plugin Updating dependency graph of PureScript bundle +2s
```
without creating the bundle.

I'm using PureScript `master`.

**Comment by ethul** [comment] 2016-02-28 13:14
I am testing this using @iand675's test repository: https://github.com/iand675/purescript-loader-reload-issue-repro

Digging into this more reveals that in some cases webpack will rebuild its bundle and in some cases it will not. For example, in the test repository, if I change [line 6](https://github.com/iand675/purescript-loader-reload-issue-repro/blob/master/src/Other.purs#L6) from "Hello wibbles" to "Hello wibbles 2", things work as expected and the webpack bundle is rebuilt.

However, if I add a line to `Other.purs` like:
```purescript
test = "a"
```

And then change the value of `test`, webpack does not update the resulting bundle. I am wondering if this is dependent on whether the PureScript bundle changes or not. For example, in the test repo, the value `other` on line 6 is used by `Main`, so changing the value causes the PureScript bundle to change, which in turn causes the webpack bundle to change.

If I add a line `test = "a"` and don't use `test` anywhere, the PureScript bundle eliminates `test` a dead code. Which means the loader is ultimately returning the same result and webpack does not need to build.

@osener I am wondering if you might be able to clone @iand675's test repo above and try the same test-case as I describe. Note that you have to install the new beta loader and plugin. The repo points to the older releases.

Also, in your project, if you remove the purescript-generated output, and run webpack without watch, does it build correctly?

Thanks for bearing with me through all of this.

**Comment by osener** [comment] 2016-02-28 13:54
Np, glad if I could be of help.

I can confirm everything you said, I'm seeing the same behavior with `"purescript-webpack-plugin": "0.2.0-beta.1"`, `"purs-loader": "0.6.0-beta.1"`, and @iand675's repo. 

I can't get my project to build, it quits halfway through the build without creating the bundle. It might be my messy config, I'll try again & narrow it down today

**Comment by ethul** [comment] 2016-02-28 14:29
Thanks for giving this a try. Let me know how it goes with your project.

I've just published `purs-loader@0.6.0-beta.2` and `purescript-webpack-plugin@0.2.0-beta.2`, can you please update to these in your testing? I found an edge case in the plugin and added an extra debug line in the loader.

Also, I am reopening this issue until we are sure things are working okay. I think the way it is working, in terms of when webpack builds, is okay. However, it may be a little confusing. Not sure ultimately the best approach, but I think I will document it in the release notes for 0.6.0. Hopefully that will be sufficient. 

Another idea is add a timestamp in the loader output so webpack always registers a change, but I don't see a reason to force webpack to build if there is no need. I am open to other thoughts on this.

**Comment by iand675** [comment] 2016-02-29 03:33
Back from the weekend:

Here's what I'm seeing when I enable the debug options on my main project. I can't seem to get the odd behavior to reproduce in the sample repo:

```
DEBUG=purescript-webpack-plugin,purs-loader ./node_modules/.bin/webpack
  purs-loader Invoke PureScript plugin compilation +0ms
  purescript-webpack-plugin Compiling PureScript files +2ms
  purs-loader Invoke PureScript plugin compilation +6ms
  purs-loader Invoke PureScript plugin compilation +1ms
  purs-loader Invoke PureScript plugin compilation +0ms
  purs-loader Invoke PureScript plugin compilation +0ms
  purs-loader Invoke PureScript plugin compilation +0ms
  purescript-webpack-plugin Bundling compiled PureScript files +694ms
  purescript-webpack-plugin Updating dependency graph of PureScript bundle +2s
```

Interestingly, if I try to use the webpack-dev-server, it never considers the bundle to be finished:

```
./node_modules/.bin/webpack-dev-server ./inner --hot --inline --module-bind "css=style\!css"
http://localhost:8080/
webpack result is served from /
content is served from /Users/foo/bar
webpack: wait until bundle finished: /bundle.js
```

When a page requests the `/bundle.js` file it just hangs there indefinitely.

I've spent a bit of time trying to duplicate the undesirable behaviour for the sample repo, but haven't had any success yet as I mentioned before. I did however notice that any build failures errors in purescript now have far worse error reporting:

```
ERROR in ./src/Main.purs
Module build failed: Error: Node does not exist: Main
    at Object.DepGraph.dependenciesOf (/Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/dependency-graph/lib/dep_graph.js:139:13)
    at dependenciesOfFn (/Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/purs-loader/index.js:3889:31)
    at /Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/purs-loader/index.js:3503:19
    at /Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/purs-loader/index.js:1981:17
    at /Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/purs-loader/index.js:120:85
    at /Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/purescript-webpack-plugin/index.js:186:76
    at Array.forEach (native)
    at /Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/purescript-webpack-plugin/index.js:186:34
    at ChildProcess.<anonymous> (/Users/ian/Code/purescript-loader-reload-issue-repro/node_modules/purescript-webpack-plugin/index.js:127:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
 @ ./entry.js 2:0-20
```

**Comment by ethul** [comment] 2016-02-29 13:45
Thanks for giving this a try @iand675 

It looks like there is an issue generating the dependency graph since the debug output stops at:
```purescript-webpack-plugin Updating dependency graph of PureScript bundle +2s```

Is there any way you can share more details on your project, or provide the `psc-bundle` output file so that I can see where it fails when the `purescript-webpack-plugin` tries to parse it?

The error you see `Error: Node does not exist: Main` is also related to the dependency graph failing to be generated. I am guessing you get this error if you project fails to build initially? Good catch on this. The error output can be updated. If your project initially builds successful and then you get a compilation error, you should get the regular `psc` error output.

**Comment by ethul** [comment] 2016-03-01 01:00
Note that `purs-loader@0.6.0-beta.3` has been released that will prefer the compilation error instead of the dependency lookup error. This means that you should see the underlying compile error instead of `Error: Node does not exist: Main`.

**Comment by ethul** [comment] 2016-03-01 01:14
@iand675  Also, I tested adding `webpack-dev-server` to your test repository, and it seems to be working okay for me. I think I will need a bit more info to determine why things are not working for your project.

**Comment by ethul** [comment] 2016-03-05 21:34
I am following up to see if anyone is experiencing any further issues or if it seems good to go in terms of making a release. Also, I've released `purescript-webpack-plugin@0.2.0-beta.3`, which caches some information to avoid having to always parse the PureScript/FFI files to get the module name. Any testing on this beta release would be most appreciated.

**Comment by ethul** [comment] 2016-03-12 20:11
I am wondering if we might be able to close this with:

`purs-loader@0.6.0-beta.4` and `purescript-webpack-plugin@0.2.0-beta.5`

**Comment by ethul** [comment] 2016-03-14 21:33
Opting to close this with the latest beta releases. Please create a new issue if there still issues with dependencies.

**Closed by ethul** 2016-03-14 21:33 UTC
Labels: type: enhancement
